name: "⭐ Feature request (request for new functionality)"
description: Help make Cmder even better
title: "[Feature request] "
labels: "🛠 Type: Feature Request"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve the Cmder project!
        ------------------------------------------------------------------

        Please make sure you read and follow the following instructions carefully before reporting bugs, and/or requesting new features.

        Make sure that you have:

        - Searched for existing issues (including the **closed** ones) for similar feature requests here:

          🗃 https://github.com/cmderdev/cmder/issues?q=is:issue

        - If you are opening the feature request regarding any of the **upstream technologies** that are used by Cmder, please open the feature request at the corresponding upstream repos instead:
            - **[Clink](https://github.com/chrisant996/clink)**, the default shell in Cmder
            - **[ConEmu](https://github.com/Maximus5/ConEmu)**, the terminal emulator
            - **[Git/MinGW](https://github.com/git-for-windows/git)**, which also provide *NIX tools (such as `ls`, `mv`, `cp`, etc)
            - **[clink-completions](https://github.com/vladimir-kotikov/clink-completions)**, which provides autocompletion for clink

        - If you would like to ask for guides on how to integrate Cmder with your favorite IDE of choice, or how to perform a specific task with Cmder, make sure you visit our label section first.

          You may already have an answer under the Guides or Questions section.

          For a list of labels, visit **[🌐 Labels](https://github.com/cmderdev/cmder/labels)**.

          (Be sure to also check “Closed” issues in the labels section!)

        - If you have a request to provide auto-complete support for a new tool, please post your request here instead:

          https://github.com/vladimir-kotikov/clink-completions/issues

        Thank you for making the Cmder project even better! ♥

  - type: textarea
    id: description
    attributes:
      label: Suggestion
      description: Describe the feature
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Include a usage example of the feature
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Extra info/examples/attachments
      description: Extra information, similar tools, etc.  If the feature is currently possible with a workaround
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all boxes that apply
      options:
        - label: I have read the documentation and made sure this feature doesn't already exist.
          required: true
        - label: I have searched for similar issues and found none that describe my feature request.
          required: true

  - type: markdown
    attributes:
      value: |
        ### Some tips on how to write a better feature request
        - Make sure the description is worded well enough to be understood, and with as much context and examples as possible.
        - Use the *Preview* tab to see how your issue will actually look like, before sending it.
          ⚠ If for some reason you can not see the text you just wrote, make sure you've read the instructions clearly
        - Please keep the ticket language to English only here.
          We can't process your issue if it's written in Russian or Chinese as we can't understand them.
